export const categoriesList = [
  'Ordinary Drink',
  'Cocktail',
  'Shake',
  'Other/Unknown',
  'Cocoa',
  'Shot',
  'Coffee/Tea',
  'Homemade Liqueur',
  'Punch/Party Drink',
  'Beer',
  'Soft Drink',
];
  // export const categoryOptions = [
  //   { value: '', label: 'categoriesList', disabled: true, hidden: true },
  //   { value: 'Ordinary Drink', label: 'Ordinary Drink' },
  //   { value: 'Shake', label: 'Shake' },
  //   { value: 'Other/Unknown', label: 'Other/Unknown' },
  //   { value: 'Cocoa', label: 'Cocoa' },
  //   { value: 'Shot', label: 'Shot' },
  //   { value: 'Coffee/Tea', label: 'Coffee/Tea' },
  //   { value: 'Homemade Liqueur', label: 'Homemade Liqueur' },
  //   { value: 'Punch/Party Drink', label: 'Punch/Party Drink' },
  //   { value: 'Beer', label: 'Beer' },
  //   { value: 'Soft Drink', label: 'Soft Drink' },
  // ];
  
  export const ingredientOptions = [
    { value: '', label: 'ingredientsList', disabled: true, hidden: true },
    { value: 'Highball glass', label: 'Highball glass' },
    { value: 'Cocktail glass', label: 'Cocktail glass' },
    { value: 'Old-fashioned glass', label: 'Old-fashioned glass' },
    { value: 'Whiskey Glass', label: 'Whiskey Glass' },
    { value: 'Collins glass', label: 'Collins glass' },
    { value: 'Pousse cafe glass', label: 'Pousse cafe glass' },
    { value: 'Champagne flute', label: 'Champagne flute' },
    { value: 'Whiskey sour glass', label: 'Whiskey sour glass' },
    { value: 'Cordial glass', label: 'Cordial glass' },
    { value: 'Brandy snifter', label: 'Brandy snifter' },
    { value: 'White wine glass', label: 'White wine glass' },
    { value: 'Nick and Nora Glass', label: 'Nick and Nora Glass' },
    { value: 'Hurricane glass', label: 'Hurricane glass' },
    { value: 'Highball glass', label: 'Highball glass' },
    { value: 'Cocktail glass', label: 'Cocktail glass' },
    { value: 'Old-fashioned glass', label: 'Old-fashioned glass' },
    { value: 'Whiskey Glass', label: 'Whiskey Glass' },
    { value: 'Collins glass', label: 'Collins glass' },
    { value: 'Pousse cafe glass', label: 'Pousse cafe glass' },
    { value: 'Champagne flute', label: 'Champagne flute' },
    { value: 'Whiskey sour glass', label: 'Whiskey sour glass' },
    { value: 'Cordial glass', label: 'Cordial glass' },
    { value: 'Brandy snifter', label: 'Brandy snifter' },
    { value: 'White wine glass', label: 'White wine glass' },
    { value: 'Nick and Nora Glass', label: 'Nick and Nora Glass' },
    { value: 'Hurricane glass', label: 'Hurricane glass' },
    { value: 'Whiskey sour glass', label: 'Whiskey sour glass' },
    { value: 'Mason jar', label: 'Mason jar' },
    { value: 'Margarita glass', label: 'Margarita glass' },
    { value: 'Martini Glass', label: 'Martini Glass' },
    { value: 'Balloon Glass', label: 'Balloon Glass' },
    { value: 'Coupe Glass', label: 'Coupe Glass' },
  ];
  export const ingredientsList = [
    'Highball glass',
    'Cocktail glass',
    'Old-fashioned glass',
    'Whiskey Glass',
    'Collins glass',
    'Pousse cafe glass',
    'Champagne flute',
    'Whiskey sour glass',
    'Cordial glass',
    'Brandy snifter',
    'White wine glass',
    'Nick and Nora Glass',
    'Hurricane glass',
    'Coffee mug',
    'Shot glass',
    'Jar',
    'Irish coffee cup',
    'Punch bowl',
    'Pitcher',
    'Pint glass',
    'Copper Mug',
    'Wine Glass',
    'Beer mug',
    'Margarita/Coupette glass',
    'Beer pilsner',
    'Beer Glass',
    'Parfait glass',
    'Mason jar',
    'Margarita glass',
    'Martini Glass',
    'Balloon Glass',
    'Coupe Glass',
  ];