export const ingredientsList = [
    'Kahlua',
    'Coffee',
    'Vodka',
    'Pisang Ambon',
    'Apple juice',
    'Lemon juice',
    'Lemonade',
    'Brandy',
    'Port',
    'Egg Yolk',
    'Coffee liqueur',
    'Light rum',
    'Ice',
    'Milk',
    'demerara Sugar',
    'Lime',
    'Cachaca',
    'Gin',
    'Vermouth',
    'Dry Vermouth',
    'Bourbon',
    'Blackberry brandy',
    'Lemon peel',
    'Jack Daniels',
    'Johnnie Walker',
    'Apricot Brandy',
    'Orange Juice',
    'Dry Vermouth',
    'Olive',
    'Applejack',
    'Triple sec',
    'Lemon juice',
    'Blended whiskey',
    'Dry Vermouth',
    'Pineapple juice',
    'Cream',
    'Ice',
    'Apple brandy',
    'Grenadine',
    'Lime',
    'Scotch',
    'Sweet Vermouth',
    'Dry Vermouth',
    'Orange bitters',
    'Baileys irish cream',
    'Frangelico',
    'zima'
  ];